version: 2

defaults: &defaults
  working_directory: /tmp/chrome-remote-desktop-image
  environment:
    GOOGLE_COMPUTE_ZONE: us-central1-a
    GOOGLE_APPLICATION_CREDENTIALS: /tmp/chrome-remote-desktop-image/workspace/packer-builder.json
    COMMIT_HASH: $(echo $CIRCLE_SHA1 | cut -c -7)

jobs:

  setup:
    <<: *defaults
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run:
          name: set up service account keys
          command: make setup
      - persist_to_workspace:
          root: workspace
          paths:
            - packer-builder.json

  unit:
    <<: *defaults
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/chrome-remote-desktop-image/workspace
      - run:
          name: Run some checks to ensure the image is ready to build
          command: make unit
    
  build:
    <<: *defaults
    docker:
      - image: hashicorp/packer
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/chrome-remote-desktop-image/workspace
      - run:
          name: Build and test image
          command: make build

workflows:
  version: 2
  image:
    jobs:
      - setup
      - unit:
          requires:
            - setup
          filters:
            branches:
              only: master
      - build:
          requires:
            - unit
          filters:
            branches:
              only: master